### PR TITLE
Lighten version API call

### PR DESCRIPTION
**Pull request by TommyDL-Infomaniak**

### CODE REVIEW

**Review by LunarX — CHANGES_REQUESTED** [review]
Is there no field in the models that we can remove now? Maybe there's even more but I think we should not need AppPublishedVersion's `_type` property anymore

**Comment by TommyDL-Infomaniak** [comment]
> While we're at it, can the AppVersion's `publishedVersions` be made into a List instead of an Array to avoid having an Array in a data class?

I made the change.

**Review by LunarX — CHANGES_REQUESTED** [review]
Didn't you show me that you also needed to modify some tests to comply with the missing `_type` property?

**Comment by TommyDL-Infomaniak** [comment]
> Didn't you show me that you also needed to modify some tests to comply with the missing `_type` property?

The tests are on Infomaniak Mail.

**Review by KevinBoulongne — APPROVED** [review]

**Review by LunarX — APPROVED** [review]

**Pull request merged**
